### ISSUE TITLE
error message command @echo OFF

### ISSUE THREAD

**Issue by sodom89** [VE3NEA/enigma-cuda#1]
Hi,

I have tried your new app on my Windows 10 PC. At the begining I got an error message, because the command console didn't know the command "@echo OFF".

I attached the whole text from the command console.

`
C:\Users\*****\Downloads\enigma-cuda-master\enigma-cuda-master\enigma-cuda\bin\x64_Release>´╗┐@echo OFF
Der Befehl "´╗┐@echo" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\******\Downloads\enigma-cuda-master\enigma-cuda-master\enigma-cuda\bin\x64_Release>enigma-cuda.exe -M H -f B:524:AA:AAA -t B:524:ZZ:ZZZ -g 013 "..\..\..\data\Tri_1941_ln.txt" "..\..\..\data\Uni_1941_ln.txt" "..\..\..\data\PBNXA.txt"
Found GPU 'GeForce GTX TITAN Black' with compute capability 3.5.
Starting at 2017-04-20 20:47:57

Spent: 00:00:00
Pass:  1
Score: 26002
Words: -2764
Key:   B:524:AA:NER
Plugs: ADBQCEFZGTIJKRNSOW
Text:  ONE gecte TEIL fhjbvqenuzgtkzfwqjocll X moegijvnbebpozjlvjsly X qv X egirqtna MAI traqpber X zmdsapeiqpaf X pvnqu okrnocudqffthfupvmhkiens X ptjeirozssehz X rb EST nikinfunufldhteroenigk X VERS enazwb BEN ffh

Spent: 00:00:00
Pass:  1
Score: 26484
Words: -2836
Key:   B:524:AD:XEO
Plugs: AUBEDQGILOMNSYWX
Text:  uesncyu DPA ceywzzebelqp X EIN ggdvvik X endpte X ernsfigeboltrhbjnneeunfv kdnneastezzijhdndgkltbet X en X st X wontsemz X ujrirbawrsofoekberkug X OST X igv X votp X yljgkofp FAN nmowrf heemzarokqcgltrilnnaftoa

Spent: 00:00:00
Pass:  1
Score: 26757
Words: -2790
Key:   B:524:AF:ZEF
Plugs: ADBGCREUFYIVJPLNOWST
Text:  cjeszsva HOB mmqeyfsjzv X stglgmpsihdvnyw HERE iodwefkrvruahyuk X EIN nis X ECHO ds X ztrzngslevswae X ig X bajcyrriersfcqw X kagalgertnvkliqtv X fkru X stenluvohlenfs X aqs X freaeuusyjywmwin X kfjkfmarzermsnyo

Spent: 00:00:00
Pass:  1
Score: 27005
Words: -2579
Key:   B:524:AQ:SEW
Plugs: BMCGDFEZIVJWKLQURX
Text:  invfnf X kolpo X iedpiierzhh X arsonfi SEI gyniqnsubzhke SAM lteiyd X duqlyrzns VIER wrdb X qquhnvntfnemunfavkyi BIG va X bjheentabel X arrifidmiz X SUN zt SAG b X drjpmuk X EINS he GENF bdsekwmg X lfugnvve GEN ubbkp X ph

Spent: 00:00:01
Pass:  1
Score: 27115
Words: -2543
Key:   B:524:AY:XEC
Plugs: BSCIEXHWKYLOMUNTPV
Text:  pyoraybs TOPF fbeeehjroeilns X pfjehzqppangswkoyyeea WEN acw X i X ggvypntineorakriht X maenfnbtqge BIER nkosru EST abage HAHN bwyyorcwntereoiz X tyrlgcpzw X mvnn ABU bjenl ICH fjmeq X zcarz DIES ENDET skrfo QUE pr

Spent: 00:00:01
Pass:  1
Score: 28275
Words: -2617
Key:   B:524:BS:HEM
Plugs: AECZFGHWIMJTKPOSRYUV
Text:  cthrzfnzv X beucutrekn LAG unujlenkesshbbpdgspnn X cqenzyc X mon WERT qekdofuedikurqvqulipd BOX pars ERST uinzhffzwa X prztwab X uowhznecfp X X ipzahtinalpzw VERS dqin X ku X gq BEN oayetereolptls INS lto X EIN ptr X

Spent: 00:00:04
Pass:  1
Score: 28385
Words: -2671
Key:   B:524:DZ:MEP
Plugs: BOCRDTFUGYHPKVLZQXSW
Text:  buvrpsgqfyppeoknekddlpz X inoevka X efungnmukrarstzezsofar DEN eel INS t DER ddvawrtibua X flsselvqu X ariqmmg X zwn LANG rulu NEN nasboerirh X ikthreikwro X phndobpyei X zwm LEGE DER vebgbcekyvldvpwlblkty SET sa

Spent: 00:00:09
Pass:  1
Score: 60917
Words: -1630
Key:   B:524:JG:YEK
Plugs: AECFGLHIKPMSNROUQYTW
Text:  iharofqs X AQT X VIER EINS X VIEL ufummsene X EINS NULL verwunti X rweyrn ZUGANG X VIER NEUN be SEE hpheuld LAZARETT EIN GESETZ owqhkdz X u TOR gosch X bhf X ut ORT X zafsoock X hock X SIEGFRIED susshqzjd X STANDARTENFUEHRER

Spent: 00:00:10
Pass:  1
Score: 71149
Words: -1433
Key:   B:524:KC:YEG
Plugs: AECFGLHIKPMSNROUQYTW
Text:  EIN rofqs X AQT X VIER EINS X VIER gefmmsene X EINS NULL verwuntete X eyrn ZUGANG X VIER NEUN BESTAND heuld LAZARETT EINGESETZT in X kdz X u TOR gosch X bhf X u TOR goscfsoock X hock X SIEGFRIED SIEG fqzjd X STANDARTENFUEHRER

Spent: 00:00:11
Pass:  1
Score: 73288
Words: -1522
Key:   B:524:KW:YEA
Plugs: AECFGLHIKPMSNROUQYTW
Text:  EINS sevub AQT X VIER EINS X VIER ge FALL oye X EINS NULL verwuntete X NEU zuk GANG X VIER NEUN BESTAND X ferzeaz ARE tt EINGESETZT in X bhfeguorgosch X bhf X u TOR gosch X hrwb X hock X SIEGFRIED SIEG friebn X t AND ARTEN FUEHRER

Spent: 00:00:11
Pass:  1
Score: 75485
Words: -1352
Key:   B:524:KX:YEB
Plugs: AECFGLHIKPMSNROUQYTW
Text:  EINS sevu X AQT X VIER EINS X VIER ge FALL oye X EINS NULL verwuntete X NEU zuu GANG X VIER NEUN BESTAND X ferz LAZARETT EINGESETZT in X bhfeg TOR gosch X bhf X u TOR gosch X hrwk X hock X SIEGFRIED SIEG friebn STANDARTENFUEHRER

Spent: 00:00:11
Pass:  1
Score: 77650
Words: -1260
Key:   B:524:KY:YEC
Plugs: AECFGLHIKPMSNROUQYTW
Text:  EINS sevs X AQT X VIER EINS X VIER ge FALL ONE X EINS NULL verwuntete X NEU z ZUGANG X VIER NEUN BESTAND X ferd LAZARETT EINGESETZT in X bhfeu TOR gosch X bhf X u TOR gosch X hrck X hock X SIEGFRIED SIEG frieb X STANDARTENFUEHRER

Spent: 00:00:11
Pass:  1
Score: 83067
Words: -1008
Key:   B:524:KZ:YED
Plugs: AECFGLHIKPMSNROUQYTW
Text:  EINS SEQS X AQT X VIER EINS X VIER GEFALLEN e X EINS NULL verwuntete X NEUN ZUGANG X VIER NEUN BESTAND X FELD LAZARETT EINGESETZT in X bhf X u TOR gosch X bhf X u TOR gosch X hock X hock X SIEGFRIED SIEGFRIED X STANDARTENFUEHRER

DONE: 1 passes in 00:00:27

C:\Users\*****\Downloads\enigma-cuda-master\enigma-cuda-master\enigma-cuda\bin\x64_Release>pause
Drücken Sie eine beliebige Taste . . .
`

**Comment by VE3NEA** [comment]
Thank you for running the test. Your 'GeForce GTX TITAN Black (compute capability 3.5) runs the program in 3x the time of GTX 1070, but still many times faster than the CPU version. And it finds the key in the first pass.

I think I will remove Echo Off from the bat file, it is not very useful anyway ;)

**Comment by VE3NEA** [comment]
The problem was not with the @Echo OFF command per se but with the UTF-8 BOM at the beginning of the .bat file that Notepad automatically added when it saved it. Fixed now.
